version: '3.8'

services:
  api:
    build: ./api
    container_name: student_api
    ports:
      - "5000:5000"
    volumes:
      - ./api/student_age.json:/data/student_age.json 
    networks:
      - student_network
    restart: unless-stopped  

  web:
   image: php:8.4.5RC1-apache
   environment:
      - USERNAME=toto
      - PASSWORD=python
   volumes:
      - ./web/index.php:/var/www/html/index.php

   ports:
      - "8080:80"
   depends_on:
      - api
   networks:
      - student_network
   restart: unless-stopped  

networks:
  student_network:
    driver: bridge
